# Generated by Django 4.1.6 on 2023-07-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorname', models.CharField(max_length=200)),
                ('expertise', models.CharField(max_length=200)),
                ('authoremail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200)),
                ('isbn_number', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('bookauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookApp.author')),
            ],
        ),
    ]
